### ISSUE TITLE
pysnesify has a PIL error

### ISSUE THREAD

**Issue by josepharaoh99** [ShadowApex/pysnesify#1]
Hey, ShadowApex, I've got a little problem here. I heard of what pysnesify could do, and I wanted to check it out. But when I ran it, it gave the following error in cmd:

line 30, in <module>
from PIL import Image
ImportError: no module name PIL

So, what can I do to fix that?

Thanks! :D

**Comment by ShadowApex** [comment]
In order to use this utility you need to install the [Pillow library](https://python-pillow.org/). Directions to install Pillow differ depending on what OS you're using, but in general if you have `pip` installed, you can install Pillow from the command line by running `pip install pillow`

**Comment by josepharaoh99** [comment]
Thanks!
I still have another problem: Python message

File "<stdin>" line 1
pip install pillow
              ^
SyntaxError: invalid syntax

**Comment by ShadowApex** [comment]
`pip install pillow` should be run from the command line, not put into a Python file.

**Comment by josepharaoh99** [comment]
Sorry, I'm such an amateur, I tried doing that, but here's what happened. I really want to get pysnesify working so I can fix some files that don't work in the game yet! Thanks in advance.
![img1](https://cloud.githubusercontent.com/assets/15201616/16779151/09a859d0-483f-11e6-9aa2-e57229f6021c.png)

**Comment by ShadowApex** [comment]
You're using `get-pip.py` incorrectly. The `get-pip.py` script is just a way for you to install pip, which is the Python package manager. Once you have installed pip, you can use the `pip` command to install Python packages.

Here's the install instructions for pip on Windows:  
https://pip.pypa.io/en/stable/installing/

Once you've successfully installed pip, you can run pip from the command line like this:  
`pip install pillow`
or
`C:\Python27\Scripts\pip.exe install pillow`

**Comment by josepharaoh99** [comment]
Really sorry to keep bugging you. I followed your instructions, found pip.exe in the Python Scripts folder, and then installed pillow. That went great. So, then I ran the pysnesify command, and got this error![untitled](https://cloud.githubusercontent.com/assets/15201616/16806962/a583ad78-48e4-11e6-9a6a-aef365182576.png)
Is there something wrong with the png extension?

**Comment by josepharaoh99** [comment]
Never mind, I finally figured it out! cmd didn't like me using brackets around the output path, that was the error. I will keep testing it out, but thanks for helping me figure this out. I couldn't have done it without you! :D Yay!
